# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9e07e99d475b9bdea8e838cbcb99f81f97d1e88385e32fc5a31e0a6ab6fd0dba143603e5568b35f2333e6c2bb0c7bcc4ecbb23a82ceeb080afc02335922d4b4

test:
  secret_key_base: 31e7b0a08446ec002ace91dd2abb8612ca684fde8bb2571f76a28b3344d00ff94b1edf5af95e6c95324871a321d7f2079b7c9ee507466851613e65bd756fd1db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
